In [2]:
import cv2
import numpy as np

### Read image

In [5]:

img = cv2.imread('images/apple.jpg', 0 )   # 0 for gray scale , 
                                    # 1 for color , 
                                    # -1 for alpha channel


In [5]:
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


### image show (imshow)

In [7]:
cv2.imshow('image', img)

# specify a wait key from keyboard
k = cv2.waitKey(0)


if k == 27: #wait for ESC key to exit
  cv2.destroyAllWindows() #close the window   

elif k == ord('s'): #if order is s save the image
  cv2.imwrite('images/image_copie.png', img) #write image in your pc     
  cv2.destroyAllWindows() # close the window     

![](images/image_copie.png)

### Show image and close it time intervale (in seconds) 

In [8]:
cv2.imshow('image', img)

# specify a wait key from keyboard
k = cv2.waitKey(5000)  # 5000 = 5 seconds
cv2.destroyAllWindows() # close the window   


### Draw geometric shapes on images

In [29]:
#img = cv2.imread('lena.jpg', 1)

# This line creates a new image with dimensions of 512x512 pixels and 3 color channels (RGB)
# All values in the image are initialized to zero using the np.zeros() function.
img = np.zeros([512, 512, 3], np.uint8)  # Zeros mean black background

# This line draws a line on the image "img" using the cv2.line() function.
# The line starts at pixel coordinates (0,0) and ends at (255,255) with a thickness of 10 pixels.
# The color of the line is specified as (214, 9, 237) which represents a shade of yellow.
img = cv2.line(img, (0,0), (255,255), (214, 9, 237), 10)
 

cv2.imshow('image', img)#show your work by window
cv2.imwrite('images/black_bg.png', img) #write image in your pc 
cv2.waitKey(0)#wait any key from keyboard    
cv2.destroyAllWindows() #close any opened window


![](images/black_bg.png)

In [30]:

img = cv2.imread('images/apple.jpg', 1)

img = cv2.line(img, (0,255), (255,255), (255, 0, 0), 10) #draw arrow

cv2.imshow('image', img)#show your work by window
cv2.imwrite('images/apple_line.png', img) #write image in your pc 
cv2.waitKey(0)#wait any key from keyboard    
cv2.destroyAllWindows() #close any opened window

#### One can also replace "line" by "arrowedLine", "rectangle", "circle", "putText", "ellipse", ...


In [26]:

img = cv2.imread('images/apple.jpg', 1)

img = cv2.arrowedLine(img, (0,255), (255,255), (255, 0, 0), 10) #draw arrow

cv2.imshow('image', img)#show your work by window
cv2.imwrite('images/apple_arrawedline.png', img) #write image in your pc 
cv2.waitKey(0)#wait any key from keyboard    
cv2.destroyAllWindows() #close any opened window

![](images/apple_line.png)

In [32]:
img = cv2.imread('images/apple.jpg', 1)

img = cv2.rectangle(img, (384, 0), (510, 128), (0, 0, 255), 10) #draw rectangle

cv2.imshow('image', img)#show your work by window
cv2.imwrite('images/apple_rectangle.png', img) #write image in your pc 
cv2.waitKey(0)#wait any key from keyboard    
cv2.destroyAllWindows() #close any opened window

![](images/apple_rectangle.png)

In [33]:
img = cv2.imread('images/apple.jpg', 1)

img = cv2.circle(img, (447, 63), 63, (0, 255, 0), -1) #draw circle

cv2.imshow('image', img)#show your work by window
cv2.imwrite('images/apple_circle.png', img) #write image in your pc 
cv2.waitKey(0)#wait any key from keyboard    
cv2.destroyAllWindows() #close any opened window

![](images/apple_circle.png)

In [38]:
img = cv2.imread('images/apple.jpg', 1)

font = cv2.FONT_HERSHEY_SIMPLEX #type of font
img = cv2.putText(img, 'Test OpenCv', (10, 500), font, 2, (38, 242, 19), 10, cv2.LINE_AA)# write a text

cv2.imshow('image', img)#show your work by window
cv2.imwrite('images/apple_text.png', img) #write image in your pc 
cv2.waitKey(0)#wait any key from keyboard    
cv2.destroyAllWindows() #close any opened window

![](images/apple_text.png)

In [39]:
img = cv2.imread('images/apple.jpg', 1)

img = cv2.ellipse(img,(256,256),(100,50),0,0,180,255,-1) #draw ellipse

cv2.imshow('image', img)#show your work by window
cv2.imwrite('images/apple_ellipse.png', img) #write image in your pc 
cv2.waitKey(0)#wait any key from keyboard    
cv2.destroyAllWindows() #close any opened window

![](images/apple_ellipse.png)