In [5]:
import cv2
import numpy as np

### Read image

In [5]:

img = cv2.imread('images/apple.jpg', 0 )   # 0 for gray scale , 
                                    # 1 for color , 
                                    # -1 for alpha channel


In [5]:
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


### image show (imshow)

In [7]:
cv2.imshow('image', img)

# specify a wait key from keyboard
k = cv2.waitKey(0)


if k == 27: #wait for ESC key to exit
  cv2.destroyAllWindows() #close the window   

elif k == ord('s'): #if order is s save the image
  cv2.imwrite('images/image_copie.png', img) #write image in your pc     
  cv2.destroyAllWindows() # close the window     

![](images/image_copie.png)

### Show image and close it time intervale (in seconds) 

In [8]:
cv2.imshow('image', img)

# specify a wait key from keyboard
k = cv2.waitKey(5000)  # 5000 = 5 seconds
cv2.destroyAllWindows() # close the window   


### Draw geometric shapes on images

In [29]:
#img = cv2.imread('lena.jpg', 1)

# This line creates a new image with dimensions of 512x512 pixels and 3 color channels (RGB)
# All values in the image are initialized to zero using the np.zeros() function.
img = np.zeros([512, 512, 3], np.uint8)  # Zeros mean black background

# This line draws a line on the image "img" using the cv2.line() function.
# The line starts at pixel coordinates (0,0) and ends at (255,255) with a thickness of 10 pixels.
# The color of the line is specified as (214, 9, 237) which represents a shade of yellow.
img = cv2.line(img, (0,0), (255,255), (214, 9, 237), 10)
 

cv2.imshow('image', img)#show your work by window
cv2.imwrite('images/black_bg.png', img) #write image in your pc 
cv2.waitKey(0)#wait any key from keyboard    
cv2.destroyAllWindows() #close any opened window


![](images/black_bg.png)

In [30]:

img = cv2.imread('images/apple.jpg', 1)

img = cv2.line(img, (0,255), (255,255), (255, 0, 0), 10) #draw arrow

cv2.imshow('image', img)#show your work by window
cv2.imwrite('images/apple_line.png', img) #write image in your pc 
cv2.waitKey(0)#wait any key from keyboard    
cv2.destroyAllWindows() #close any opened window

#### One can also replace "line" by "arrowedLine", "rectangle", "circle", "putText", "ellipse", ...


In [26]:

img = cv2.imread('images/apple.jpg', 1)

img = cv2.arrowedLine(img, (0,255), (255,255), (255, 0, 0), 10) #draw arrow

cv2.imshow('image', img)#show your work by window
cv2.imwrite('images/apple_arrawedline.png', img) #write image in your pc 
cv2.waitKey(0)#wait any key from keyboard    
cv2.destroyAllWindows() #close any opened window

![](images/apple_line.png)

In [32]:
img = cv2.imread('images/apple.jpg', 1)

img = cv2.rectangle(img, (384, 0), (510, 128), (0, 0, 255), 10) #draw rectangle

cv2.imshow('image', img)#show your work by window
cv2.imwrite('images/apple_rectangle.png', img) #write image in your pc 
cv2.waitKey(0)#wait any key from keyboard    
cv2.destroyAllWindows() #close any opened window

![](images/apple_rectangle.png)

In [33]:
img = cv2.imread('images/apple.jpg', 1)

img = cv2.circle(img, (447, 63), 63, (0, 255, 0), -1) #draw circle

cv2.imshow('image', img)#show your work by window
cv2.imwrite('images/apple_circle.png', img) #write image in your pc 
cv2.waitKey(0)#wait any key from keyboard    
cv2.destroyAllWindows() #close any opened window

![](images/apple_circle.png)

In [38]:
img = cv2.imread('images/apple.jpg', 1)

font = cv2.FONT_HERSHEY_SIMPLEX #type of font
img = cv2.putText(img, 'Test OpenCv', (10, 500), font, 2, (38, 242, 19), 10, cv2.LINE_AA)# write a text

cv2.imshow('image', img)#show your work by window
cv2.imwrite('images/apple_text.png', img) #write image in your pc 
cv2.waitKey(0)#wait any key from keyboard    
cv2.destroyAllWindows() #close any opened window

![](images/apple_text.png)

In [39]:
img = cv2.imread('images/apple.jpg', 1)

img = cv2.ellipse(img,(256,256),(100,50),0,0,180,255,-1) #draw ellipse

cv2.imshow('image', img)#show your work by window
cv2.imwrite('images/apple_ellipse.png', img) #write image in your pc 
cv2.waitKey(0)#wait any key from keyboard    
cv2.destroyAllWindows() #close any opened window

![](images/apple_ellipse.png)

## Handle Mouse Events 

In [8]:
import numpy as np
import cv2

# events = [i for i in dir(cv2) if 'EVENT' in  i]
# print(events)

def click_event(event, x, y, flags, param):
    if event == cv2.EVENT_LBUTTONDOWN:
        print(x,', ' ,y)
        font = cv2.FONT_HERSHEY_SIMPLEX
        strXY = str(x) + ', '+ str(y)
        cv2.putText(img, strXY, (x, y), font, .5, (255, 255, 0), 2)
        cv2.imshow('image', img)
    if event == cv2.EVENT_RBUTTONDOWN:
        blue = img[y, x, 0]
        green = img[y, x, 1]
        red = img[y, x, 2]
        font = cv2.FONT_HERSHEY_SIMPLEX
        strBGR = str(blue) + ', '+ str(green)+ ', '+ str(red)
        cv2.rectangle(img, (x, y+5), (x+110, y-15), (198, 201, 197), -1)
        cv2.putText(img, strBGR, (x, y), font, .5, (0, 255, 255), 2)
        cv2.imshow('image', img)


img = cv2.imread('images/apple.jpg')
cv2.imshow('image', img)

cv2.setMouseCallback('image', click_event)

cv2.waitKey(0)
cv2.destroyAllWindows()

275 ,  268
185 ,  336
277 ,  432
471 ,  398
120 ,  252
125 ,  184
496 ,  118


![](images/Handle%20Mouse.png)

In [4]:
# import the necessary libraries
import numpy as np
import cv2

# define the callback function for mouse events
def click_event(event, x, y, flags, param):
    # check if left button is clicked
    if event == cv2.EVENT_LBUTTONDOWN:
        # draw a small blue circle where the user clicked
        cv2.circle(img, (x,y), 3, (255,0,0), -1)
        # add text showing the coordinates of the click
        font = cv2.FONT_HERSHEY_SIMPLEX
        strXY = str(x) + ', '+ str(y)
        cv2.putText(img, strXY, (x, y), font, .5, (255, 255, 0), 2)

        # add the clicked point to a list
        points.append((x,y))
        # if there are at least two points, draw a line between the last two points
        if len(points) >= 2:
            cv2.line(img, points[-1], points[-2], (0,255,255))
        # show the updated image with circles and lines
        cv2.imshow('Click Event', img)

# create a black image using numpy with 512 x 512 resolution and 3 channels (RGB)
img = np.zeros((512, 512,3) , np.uint8)

# show the blank image
cv2.imshow('Click Event', img)

# create an empty list to store clicked points
points = []

# set the mouse callback function to the click_event function
cv2.setMouseCallback('Click Event', click_event)

# wait for a key event (in this case, any key) to exit the program
cv2.waitKey(0)

# destroy all windows created by OpenCV
cv2.destroyAllWindows()


![](images/click_event.png)

### get colorRGB

In [17]:
# import the necessary libraries
import numpy as np
import cv2

# define the callback function for mouse events
def click_and_get_color(event, x, y, flags, param):
    # check if left button is clicked
    if event == cv2.EVENT_LBUTTONDOWN:
        blue = img[x, y, 0]
        green = img[x, y, 1]
        red = img[x, y, 2]
        colorRGB = np.zeros((512, 512, 3), dtype = np.uint8)
        colorRGB[ : ] = [blue, green, red]

        font = cv2.FONT_HERSHEY_SIMPLEX
        strBGR = str(blue) + ', '+ str(green)+ ', '+ str(red)
        colorRGB = cv2.putText(colorRGB, strBGR , (10, 50), font, 2, (38, 242, 19), 5, cv2.LINE_AA)

        cv2.imshow("colorRGB", colorRGB)

        

img = cv2.imread('images/apple.jpg')
cv2.imshow("Apple", img)

# set the mouse callback function to the click_event function
cv2.setMouseCallback('Apple', click_and_get_color)

# wait for a key event (in this case, any key) to exit the program
cv2.waitKey(0)

# destroy all windows created by OpenCV
cv2.destroyAllWindows()


![](images/colorRGB.png)

### cv2 createTrackbar

In [4]:
import cv2
import numpy as np

def on_trackbar(val):
    # Function that gets called whenever the trackbar is moved
    print("Value of trackbar is:", val)

# Create a black image and a window
img = np.zeros((51,512,3), np.uint8)
cv2.namedWindow('image')

# Create a trackbar
cv2.createTrackbar('value', 'image', 0, 255, on_trackbar)

while(1):
    cv2.imshow('image',img)
    k = cv2.waitKey(1) & 0xFF
    if k == 27:  # Escape key to exit
        break

    # Get the current position of the trackbar
    val = cv2.getTrackbarPos('value', 'image')

    # Update the image with the current value of the trackbar
    img[:] = [val,val,val]

cv2.destroyAllWindows()


Value of trackbar is: 1
Value of trackbar is: 4
Value of trackbar is: 11
Value of trackbar is: 17
Value of trackbar is: 24
Value of trackbar is: 29
Value of trackbar is: 34
Value of trackbar is: 38
Value of trackbar is: 40
Value of trackbar is: 42
Value of trackbar is: 45
Value of trackbar is: 47
Value of trackbar is: 50
Value of trackbar is: 52
Value of trackbar is: 54
Value of trackbar is: 55
Value of trackbar is: 57
Value of trackbar is: 60
Value of trackbar is: 63
Value of trackbar is: 65
Value of trackbar is: 67
Value of trackbar is: 68
Value of trackbar is: 69
Value of trackbar is: 71
Value of trackbar is: 73
Value of trackbar is: 75
Value of trackbar is: 77
Value of trackbar is: 79
Value of trackbar is: 80
Value of trackbar is: 82
Value of trackbar is: 83
Value of trackbar is: 84
Value of trackbar is: 85
Value of trackbar is: 86
Value of trackbar is: 87
Value of trackbar is: 88
Value of trackbar is: 89
Value of trackbar is: 90
Value of trackbar is: 91
Value of trackbar is: 92
Va

![](images/createTrackbar.png)

In [6]:
import cv2

import numpy as np



def nothing(x):

    pass    



cv2.namedWindow("Tracking")

cv2.createTrackbar("LH", "Tracking", 0, 255, nothing)

cv2.createTrackbar("LS", "Tracking", 0, 255, nothing)

cv2.createTrackbar("LV", "Tracking", 0, 255, nothing)

cv2.createTrackbar("UH", "Tracking", 255, 255, nothing)

cv2.createTrackbar("US", "Tracking", 255, 255, nothing)

cv2.createTrackbar("UV", "Tracking", 255, 255, nothing)



while True:

    frame = cv2.imread('images/apple.jpg')      



    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)       



    l_h = cv2.getTrackbarPos("LH", "Tracking")       

    l_s = cv2.getTrackbarPos("LS", "Tracking")       

    l_v = cv2.getTrackbarPos("LV", "Tracking")       



    u_h = cv2.getTrackbarPos("UH", "Tracking")       

    u_s = cv2.getTrackbarPos("US", "Tracking")       

    u_v = cv2.getTrackbarPos("UV", "Tracking")       



    l_b = np.array([l_h, l_s, l_v])       

    u_b = np.array([u_h, u_s, u_v])       



    mask = cv2.inRange(hsv, l_b, u_b)       



    res = cv2.bitwise_and(frame, frame, mask=mask)        



    cv2.imshow("frame", frame)        

    cv2.imshow("mask", mask)        

    cv2.imshow("res", res)        



    key = cv2.waitKey(1)         

    if key == 27:        

        break               



cv2.destroyAllWindows() #colse window

![](images/trackbar.png)